version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server

  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    depends_on:
      - backend
