version: '3'

services:
  backend:
    image: harshiniprojects.azurecr.io/snappy-chat-app-backend-2.0:latest
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server

  frontend:
    image: harshiniprojects.azurecr.io/snappy-chat-app-frontend-2.0:latest
    build:
      context: ./public
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    depends_on:
      - backend
