name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Azure Login
        run: |
          echo "##[group]Login to Azure"
          az login --service-principal --username ${{ secrets.ARM_CLIENT_ID }} --password ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
          echo "##[endgroup]"

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: 'harshiniprojects.azurecr.io'
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - uses: azure/container-apps-deploy-action@v1
        with:
          azureContainerRegistry: harshiniprojects
          imageToDeploy: harshiniprojects.azurecr.io/snappy-chat-app-frontend-2.0:latest
          containerAppName: snappy-container
          resourceGroup: Harshini-Training
